name: Bug Report
description: 'Any bug about core nzbget, EXCLUDING extensions, performance issues or compiling nzbget.'
labels: ['bug']
body:
- type: checkboxes
  attributes:
    label: Is there already an issue for your problem?
    description: Please make sure you are not creating an already submitted <a href="https://github.com/nzbgetcom/nzbget/issues">Issue</a>. Check closed issues as well, because your issue may have already been fixed.
    options:
      - label: I have checked older issues, open and closed
        required: true
- type: dropdown
  attributes:
    label: NZBGet Version
    description: Which version of NZBGet has this bug?
    options:
    - v24.1-stable
    - v24.1-testing
    - v24-stable
    - v24-testing
    - v23-stable
    - v23-testing
    - v22-stable (nzbgetcom takeover)
    - v22-testing (nzbgetcom takeover)
    - v21 or earlier (orignal nzbget)
    - latest-stable (if not listed here)
    - latest-testing (if not listed here)
  validations:
    required: true
- type: dropdown
  attributes:
    label: Platform
    description: Select a specific platform for this bug report, choose All if it applies to all platforms
    options:
    - All
    - Windows
    - macOS
    - NAS/Synology/QNAP
    - Linux/Docker
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: Please provide the details of the system NZBGet is running on. The more information you can provide, the better
    placeholder: |
      Device:
      OS version: platform n.nn (32bit/64bit)
      CPU architecture: (32bit/64bit)
      Includes libs or tool that apply: 7zip x.x, unrar x.x, python3.11
      Running in Docker: No/Yes
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Logs
    description: |
      Any logs or messages that apply
  validations:
    required: false
- type: textarea
  attributes:
    label: Extra information
    description: |
      Please refer to any extra information - extra documentation, attach files or images
  validations:
    required: false