#!/bin/bash

case ${MakeClean} in
	[Yy][Ee][Ss])        
		make clean
		;;
esac

case ${CleanOnly} in
	[Yy][Ee][Ss])
		return
		;;
esac

export CC="$CC"
export CXX="$CXX"
export LD="$LD"
export AR="$AR"
export STRIP="$STRIP"
export RANLIB="$RANLIB"
export NM="$NM"
export CFLAGS="$CFLAGS -Os"
export CXXFLAGS="$CXXFLAGS"
export LDFLAGS="$LDFLAGS"

# build boost library
cd ./tmp/boost
./bootstrap.sh --with-libraries=json --prefix=$(pwd)/build
echo "using gcc : synology : $CC ; " >>  project-config.jam
./b2 --toolset=gcc-synology cxxstd=14 link=static runtime-link=static install
cd ../..

autoreconf --install

# prefix with /usr/local, all files will be installed into /usr/local
export CXXFLAGS="$CXXFLAGS -I$(pwd)/tmp/boost/build/include"
export LDFLAGS="$LDFLAGS -L$(pwd)/tmp/boost/build/lib"
./configure $ConfigOpt --prefix=/usr/local --program-prefix="" --program-suffix=""

make -j 2 ${MAKE_FLAGS}

make install
