#!/bin/sh
. `dirname $0`/vars

# check conf file location, copy if not exist
# and populate from synology defaults
if [ ! -f $CFG ]; then
    cp $SYNOPKG_PKGDEST/usr/local/share/nzbget/nzbget.conf $CFG
    if [ -z "$wizard_download_subfolder" ]; then
        DOWNLOAD_PATH=$wizard_download_folder
    else
        DOWNLOAD_PATH=$wizard_download_folder/$wizard_download_subfolder
    fi
    sed -e "s|MainDir=.*$|MainDir=/var/packages/nzbget/shares/$DOWNLOAD_PATH|g" \
        -e "s/ControlUsername=.*$/ControlUsername=$wizard_username/g" \
        -e "s/ControlPassword=.*$/ControlPassword=$wizard_password/g" \
        -e "s|WebDir=.*$|WebDir=$SYNOPKG_PKGDEST/usr/local/share/nzbget/webui|g" \
        -e "s|LogFile=.*$|LogFile=$SYNOPKG_PKGVAR/nzbget.log|g" \
        -e "s|LockFile=.*$|LockFile=$SYNOPKG_PKGVAR/nzbget.lock|g" \
        -e "s|ConfigTemplate=.*$|ConfigTemplate=$SYNOPKG_PKGDEST/usr/local/share/nzbget/nzbget.conf|g" \
        -i $CFG
    # copy bundled scripts
    mkdir -p /var/packages/nzbget/shares/$DOWNLOAD_PATH/scripts/
    cp $SYNOPKG_PKGDEST/usr/local/share/nzbget/scripts/* /var/packages/nzbget/shares/$DOWNLOAD_PATH/scripts/
fi

exit 0
