#!/bin/sh
. `dirname $0`/vars

case $1 in
	start)
		### Start this package.
		$NZBGET -D -c $CFG
		echo "nzbget has been started" > $SYNOPKG_TEMP_LOGFILE
		exit 0
	;;
	stop)
		### Stop this package.
		$NZBGET -Q -c $CFG
		echo "nzbget has been stopped" > $SYNOPKG_TEMP_LOGFILE
		exit 0
	;;
	status)
		### Check package alive.
		if [ -z $(ps aux | grep $NZBGET | grep -v "grep $NZBGET") ]; then
			exit 1;
		else
			exit 0;
		fi
	;;
esac
