if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|AppleClang")
		add_compile_options(-Weverything -Wno-c++98-compat)
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		add_compile_options(-Wall -Wextra)
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		add_compile_options(/Zi /MTd /MP /EHs /W4 /utf-8)
	endif()
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
	if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		add_compile_options(/MT /Oi /MP /EHs /GR- /W0 /utf-8)
	else()
		add_compile_options(-fno-rtti -Wno-unused-function -Wno-unused-variable -Wno-unused-parameter)
		if(NOT CMAKE_SYSTEM_PROCESSOR STREQUAL "powerpc")
			add_compile_options(-fstack-protector)
		endif()
	endif()

	if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|AppleClang")
		add_compile_options(-Wno-c++98-compat)
	endif()
endif()

include(ExternalProject)
