if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|AppleClang")
		set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g -Weverything -Wno-c++98-compat")
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		set(CMAKE_CXX_FLAGS "-O0 -g -Wall -Wextra")
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		set(CMAKE_CXX_FLAGS "/Od /Zi /MP /W4 /DDEBUG /D_DEBUG /wd4800 /wd4267")
		set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} winmm.lib Dbghelp.lib libcpmtd.lib")
		set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDebug")
	endif()
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
	if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|AppleClang")
		set(CMAKE_CXX_FLAGS "-O2 -DNDEBUG -Weverything -Wno-c++98-compat")
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		set(CMAKE_CXX_FLAGS "-O2 -DNDEBUG -Wall -Wextra")
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		set(CMAKE_CXX_FLAGS "/O2 /MP /W4 /DNDEBUG /wd4800 /wd4267")
		set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} winmm.lib")
		set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded")
	endif()
endif()

set(CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS} CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS} CACHE STRING "" FORCE)

if(NOT WIN32)
	if(CMAKE_SYSTEM_PROCESSOR MATCHES "i?86|x86_64")
		set(SSE2_CXXFLAGS "-msse2")
		set(SSSE3_CXXFLAGS "-mssse3")
		set(PCLMUL_CXXFLAGS "-msse4.1 -mpclmul")
	elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm*")
		set(NEON_CXXFLAGS "-mfpu=neon")
		set(ACLECRC_CXXFLAGS "-march=armv8-a+crc -fpermissive")
	elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
		set(ACLECRC_CXXFLAGS "-march=armv8-a+crc -fpermissive")
	endif()
endif()
