set(DOC_FILES 
	${CMAKE_SOURCE_DIR}/ChangeLog	
	${CMAKE_SOURCE_DIR}/COPYING
)
set(CONF_FILE ${CMAKE_SOURCE_DIR}/nzbget.conf)
set(WEBUI_DIR ${CMAKE_SOURCE_DIR}/webui)
set(BIN_FILE  ${CMAKE_BINARY_DIR}/${PACKAGE})
set(DOC_FILES_DEST ${CMAKE_INSTALL_PREFIX}/share/doc)
set(CONF_FILE_DEST ${CMAKE_INSTALL_PREFIX}/share)
set(WEBUI_DIR_DEST ${CMAKE_INSTALL_PREFIX}/share/nzbget)
set(BIN_FILE_DEST ${CMAKE_INSTALL_PREFIX}/bin)

install(FILES ${BIN_FILE} DESTINATION ${BIN_FILE_DEST})
install(FILES ${DOC_FILES} DESTINATION ${DOC_FILES_DEST})
install(DIRECTORY ${WEBUI_DIR} DESTINATION ${WEBUI_DIR_DEST})

file(READ ${CONF_FILE} CONFIG_CONTENT)
string(REPLACE "WebDir=" "WebDir=${WEBUI_DIR_DEST}/webui" MODIFIED_CONFIG_CONTENT "${CONFIG_CONTENT}")
string(REPLACE "ConfigTemplate=" "ConfigTemplate=${CONF_FILE_DEST}/nzbget.conf" MODIFIED_CONFIG_CONTENT "${MODIFIED_CONFIG_CONTENT}")
file(WRITE ${CONF_FILE_DEST}/nzbget.conf "${MODIFIED_CONFIG_CONTENT}")
