set(RAPIDYENC_ROOT ${CMAKE_BINARY_DIR}/rapidyenc/src)
if(CMAKE_GENERATOR MATCHES "Visual Studio") 
	set(RAPIDYENC_LIBS
		${RAPIDYENC_ROOT}/rapidyenc-build/rapidyenc_static/${CMAKE_BUILD_TYPE}/rapidyenc.lib
	)
elseif(CMAKE_GENERATOR MATCHES "Xcode")
	set(RAPIDYENC_LIBS
		${RAPIDYENC_ROOT}/rapidyenc-build/rapidyenc_static/${CMAKE_BUILD_TYPE}/librapidyenc.a
	)
else()
	set(RAPIDYENC_LIBS
		${RAPIDYENC_ROOT}/rapidyenc-build/rapidyenc_static/librapidyenc.a
	)
endif()

set(CMAKE_ARGS
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	-DCMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}
	-DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}
	-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
	-DDISABLE_SHARED_LIB=ON
	-DDISABLE_CLI=ON
	-DDISABLE_BENCH_CLI=ON
)

if(DEFINED TOOLCHAIN_PREFIX)
	set(CMAKE_ARGS ${CMAKE_ARGS} -DTOOLCHAIN_PREFIX=${TOOLCHAIN_PREFIX})
endif()

if(APPLE)
	set(CMAKE_ARGS ${CMAKE_ARGS}
		-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
	)
endif()

if(CMAKE_SYSROOT)
	set(CMAKE_ARGS ${CMAKE_ARGS}
		-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
		-DCMAKE_SYSROOT=${CMAKE_SYSROOT}
		-DCMAKE_CXX_FLAGS=-I${CMAKE_SYSROOT}/usr/include/c++/v1
	)
endif()

ExternalProject_add(
	rapidyenc
	PREFIX			rapidyenc
	GIT_REPOSITORY	https://github.com/nzbgetcom/rapidyenc.git
	GIT_TAG			nzbget
	TLS_VERIFY		TRUE
	GIT_SHALLOW		TRUE
	GIT_PROGRESS	TRUE
	DOWNLOAD_EXTRACT_TIMESTAMP	TRUE
	BUILD_BYPRODUCTS ${RAPIDYENC_LIBS}
	CMAKE_ARGS		 ${CMAKE_ARGS}
	INSTALL_COMMAND	""
)

set(LIBS ${LIBS} ${RAPIDYENC_LIBS})
set(INCLUDES ${INCLUDES} ${RAPIDYENC_ROOT}/rapidyenc)
