set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ${ARCH})

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_AR           ${TOOLCHAIN_PATH}$${TARGET_TRIPLET}-ar)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PATH}$${TARGET_TRIPLET}-as)
set(CMAKE_C_COMPILER   ${TOOLCHAIN_PATH}$${TARGET_TRIPLET}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}$${TARGET_TRIPLET}-g++)
set(CMAKE_LINKER       ${TOOLCHAIN_PATH}$${TARGET_TRIPLET}-ld)
set(CMAKE_OBJCOPY      ${TOOLCHAIN_PATH}$${TARGET_TRIPLET}-objcopy)
set(CMAKE_RANLIB       ${TOOLCHAIN_PATH}$${TARGET_TRIPLET}-ranlib)
set(CMAKE_SIZE         ${TOOLCHAIN_PATH}$${TARGET_TRIPLET}-size)
set(CMAKE_STRIP        ${TOOLCHAIN_PATH}$${TARGET_TRIPLET}-strip)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
