option(ENABLE_TESTS "Enable tests")
option(DISABLE_TLS "Disable TLS")

message(STATUS "Options:")
message(STATUS "  BUILD_TYPE:   ${CMAKE_BUILD_TYPE}")
message(STATUS "  ENABLE_TESTS: ${ENABLE_TESTS}")
message(STATUS "  DISABLE_TLS:  ${DISABLE_TLS}")

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		set(CMAKE_CXX_FLAGS "-O0 -g -Wall -Wextra" CACHE STRING "" FORCE)
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		set(CMAKE_CXX_FLAGS "/Od /Zi /MP /W4 /DDEBUG /D_DEBUG /wd4800 /wd4267" CACHE STRING "" FORCE)
		set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} winmm.lib Dbghelp.lib libcpmtd.lib" CACHE STRING "" FORCE)
		set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDebug" CACHE STRING "" FORCE)
	endif()
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
	if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		set(CMAKE_CXX_FLAGS "-O2 -DNDEBUG -Wall -Wextra" CACHE STRING "" FORCE)
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		set(CMAKE_CXX_FLAGS "/O2 /MP /W4 /DNDEBUG /wd4800 /wd4267" CACHE STRING "" FORCE)
		set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} winmm.lib" CACHE STRING "" FORCE)
		set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded" CACHE STRING "" FORCE)
	endif()
endif()

set(CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS} CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS} CACHE STRING "" FORCE)
add_subdirectory(${CMAKE_SOURCE_DIR}/lib)

target_link_libraries(${PACKAGE} PRIVATE Par2)
target_include_directories(${PACKAGE} PRIVATE ${CMAKE_SOURCE_DIR}/lib/par2)

if(NOT DISABLE_TLS)
	find_package(OpenSSL REQUIRED)
	set(HAVE_OPENSSL 1)
	set(HAVE_X509_CHECK_HOST 1)
	target_link_libraries(${PACKAGE} PRIVATE OpenSSL::SSL OpenSSL::Crypto)
	target_include_directories(${PACKAGE} PRIVATE ${OPENSSL_INCLUDE_DIR})
endif()

find_package(ZLIB REQUIRED)
target_link_libraries(${PACKAGE} PRIVATE ZLIB::ZLIB)
target_include_directories(${PACKAGE} PRIVATE ${ZLIB_INCLUDE_DIRS})

target_include_directories(${PACKAGE} PRIVATE
	${CMAKE_SOURCE_DIR}/daemon/windows
	${CMAKE_SOURCE_DIR}/windows/resources
)
target_sources(${PACKAGE} PRIVATE ${CMAKE_SOURCE_DIR}/windows/resources/nzbget.rc)

set(FUNCTION_MACRO_NAME __FUNCTION__)
set(HAVE_CTIME_R_3 1)
set(HAVE_VARIADIC_MACROS 1)
set(HAVE_GETADDRINFO 1)
set(SOCKLEN_T socklen_t)
set(HAVE_REGEX_H 1)

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
	set(__amd64__ 1)
else()
	set(__i686__ 1) 
	set(_USE_32BIT_TIME_T 1) 
endif()

if(NOT DISABLE_SIGCHLD_HANDLER)
	set(SIGCHLD_HANDLER 1) 
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	set(_CRTDBG_MAP_ALLOC 1) 
endif()
