name: docker build

on:
  push:
    branches:
    - main
    tags:
    - "v*"
  workflow_call:
    inputs:
      debug:
        description: 'Build debug version'
        type: boolean
        required: false
        default: false
  workflow_dispatch:

env:
  REGISTRY_IMAGE: nzbgetcom/nzbget

jobs:

  prepare:
    runs-on: ubuntu-24.04
    outputs:
      build_type: ${{ steps.set-build-type.outputs.build_type }}
    steps:
      - name: Set build type
        id: set-build-type
        run: |
          if [[ "${{ inputs.debug }}" == "true" ]]; then
            echo "build_type=Debug" >> $GITHUB_OUTPUT
          else
            echo "build_type=Release" >> $GITHUB_OUTPUT
          fi

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm/v7
            runner: ubuntu-24.04-arm
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    needs: prepare
    steps:

      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Prepare
        id: prepare
        run: |
          platform=${{ matrix.platform }}
          echo "platform-slug=${platform//\//-}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          file: docker/Dockerfile
          platforms: ${{ matrix.platform }}
          provenance: false
          outputs: "type=image,oci-mediatypes=false,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true"
          build-args: |
            "MAKE_JOBS=4"
            "CMAKE_BUILD_TYPE=${{ needs.prepare.outputs.build_type }}"

      - name: Export digest
        run: |
          rm -rf digests
          mkdir -p digests
          digest="${{ steps.build.outputs.digest }}"
          touch "digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: digests-${{ needs.prepare.outputs.build_type }}-${{ steps.prepare.outputs.platform-slug }}
          path: digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-24.04
    needs: [prepare,build]
    permissions:
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Download digests
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: digests
          pattern: digests-${{ needs.prepare.outputs.build_type }}-*
          merge-multiple: true

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        id: gen-tag
        run: |
          case $GITHUB_REF_NAME in
            develop)
              TAG="testing"
              ;;
            main)
              TAG="latest"
              ;;
            refs/tags/*)
              TAG="${GITHUB_REF/refs\/tags\//}"
              ;;
            *)
              TAG="${GITHUB_REF_NAME/\//-}"
              ;;
          esac
          if [[ "${{ inputs.debug }}" == "true" ]]; then
            if [[ "$GITHUB_REF_NAME" == "develop" ]]; then
              TAG="debug"
            else
              TAG="$TAG-debug"
            fi
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Create manifest list, push and inspect
        run: |
          cd digests
          docker manifest create ${{ env.REGISTRY_IMAGE }}:${{ steps.gen-tag.outputs.tag }} $(printf -- '--amend ${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
          docker manifest push ${{ env.REGISTRY_IMAGE }}:${{ steps.gen-tag.outputs.tag }}
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.gen-tag.outputs.tag }}
          if [[ "$GITHUB_REF_NAME" == "develop" ]] || [[ "$GITHUB_REF_NAME" == "main" ]] || [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            docker buildx imagetools create -t ghcr.io/${{ env.REGISTRY_IMAGE }}:${{ steps.gen-tag.outputs.tag }} ${{ env.REGISTRY_IMAGE }}:${{ steps.gen-tag.outputs.tag }}
            docker buildx imagetools inspect ghcr.io/${{ env.REGISTRY_IMAGE }}:${{ steps.gen-tag.outputs.tag }}
          fi

      - name: Update Docker Hub Description
        if: github.ref_name == 'main'
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.REGISTRY_IMAGE }}
          readme-filepath: ./docker/README.md

      - name: Cleanup ghcr.io from outdated images
        uses: miklinux/ghcr-cleanup-action@5c95ee8945fd81f837669635a20ea2f2b751c477 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-owner: nzbgetcom
          package-name: nzbget
          delete-orphans: true
          dry-run: false

      - name: Delete unneeded digests artifacts
        uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6
        with:
          name: digests-${{ needs.prepare.outputs.build_type }}-*
