name: flatpak

on:
  workflow_call:
    inputs:
      external_call:
        description: 'To distinguish workflow_call from regular push / workflow_dispatch'
        type: boolean
        required: false
        default: false
  workflow_dispatch:

jobs:
  build-linux:
    uses: ./.github/workflows/linux.yml
    if: ${{ inputs.external_call == false }}

  build-flatpak:
    runs-on: ubuntu-24.04
    needs: [build-linux]
    if: always()
    permissions:
      actions: write

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4

    - name: Build Flatpak packages
      run: |
        sudo apt-get update
        sudo apt-get install flatpak flatpak-builder appstream-compose -y
        bash linux/flatpak/build-flatpak.sh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nzbget-flatpak-packages
        path: build/flatpak/*.flatpak
        retention-days: 5

    - name: Delete unneeded linux artifacts
      if: ${{ inputs.external_call == false }}
      uses: geekyeggo/delete-artifact@v4
      with:
        name: |
          nzbget-linux-installers
