name: freebsd build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare freebsd build environment
      run: |
        sudo mkdir -p /build
        sudo chown $USER:$USER /build
        mkdir -p /build/freebsd
        mkdir -p /build/lib
        curl -L https://github.com/nzbgetcom/build-files/releases/download/v1.0/freebsd-sysroot.tar.gz -o /build/freebsd/sysroot.tar.gz
        curl -L https://github.com/nzbgetcom/build-files/releases/download/v1.0/lib-x86_64-bsd.tar.gz -o /build/lib/lib.tar.gz
        tar zxf /build/freebsd/sysroot.tar.gz -C /build/freebsd
        tar zxf /build/lib/lib.tar.gz -C /build/lib
        sudo apt-get install -y autoconf automake bc build-essential cmake cpio curl file git libtool pkg-config rsync unzip wget libtinfo5 clang-14

    - name: Build
      run: |
        BUILD_PARAMS="freebsd bin installer"
        if [ "$GITHUB_REF_NAME" == "develop" ] || [ "$GITHUB_REF_NAME" == "main" ]; then
          BUILD_PARAMS="$BUILD_PARAMS debug release"
        else
          BUILD_PARAMS="$BUILD_PARAMS release"
        fi
        if [ "$GITHUB_REF_NAME" != "main" ]; then
          BUILD_PARAMS="$BUILD_PARAMS testing"
        fi
        bash linux/build-nzbget.sh $BUILD_PARAMS

    - name: Upload full build log on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: nzbget-freebsd-build-log
        path: build/*/build.log
        retention-days: 5

    - name: Rename build artifacts
      if: github.ref_name != 'main' && github.ref_name != 'develop'
      run: |
        cd build
        SUFFIX="-${GITHUB_REF_NAME/\//-}-bin-freebsd.run"
        for FILE in *.run; do
          [ -f $FILE ] || continue
          NEW_FILE=${FILE/-bin-freebsd.run/$SUFFIX}
          mv $FILE $NEW_FILE
        done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nzbget-freebsd-installers
        path: build/*.run
        retention-days: 5
