name: qnap build 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, nzbget-qnap]

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Save version for non-release to env
      if: github.ref_name != 'main'
      run: |
        VERSION=$(cat configure.ac | grep AC_INIT | cut -d , -f 2 | xargs)
        echo VERSION=$VERSION >> $GITHUB_ENV

    - name: Build
      run: |
        export PATH="$PATH:/usr/share/QDK/bin"
        bash qnap/build-nzbget.sh

    - name: Rename build artifacts
      if: github.ref_name != 'main'
      run: |
        cd /qnap/nzbget/build/
        NEW_VERSION="$VERSION-testing-$(date '+%Y%m%d')"
        for FILE in *.qpkg; do
          [ -f $FILE ] || continue
          NEW_FILE=${FILE/$VERSION/$NEW_VERSION}
          sudo mv $FILE $NEW_FILE          
        done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nzbget-qnap-native-packages
        path: /qnap/nzbget/build/*.qpkg
        retention-days: 5

    - name: Cleanup
      run: |
        rm -rf /qnap/nzbget/
