name: release

on:
  workflow_run:
    workflows: [linux, windows, osx]
    types:
    - completed

jobs:
  gen-sigs:
    runs-on: [self-hosted, linux]

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
    

    - name: Download build arfifacts
      uses: actions/github-script@v6
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.payload.workflow_run.id,
          });
          for (artifact in allArtifacts) {
            let download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifact.id,
              archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`/tmp/${artifact.id}.zip`, Buffer.from(download.data));
          }          
          
