name: synology build 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, nzbget-synology]

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: |
        sudo -E bash synology/build-nzbget.sh

    - name: Rename build artifacts
      if: github.ref_name != 'main'
      run: |
        cd /toolkit/result_spk/nzbget/
        VERSION=$(date '+%Y%m%d')
        NEW_VERSION="$VERSION-testing"
        for FILE in *.spk; do
          [ -f $FILE ] || continue
          NEW_FILE=${FILE/$VERSION/$NEW_VERSION}
          sudo mv $FILE $NEW_FILE          
        done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nzbget-synology-packages
        path: /toolkit/result_spk/nzbget/*.spk
        retention-days: 5

    - name: Cleanup
      run: |
        sudo rm /toolkit/result_spk/nzbget/*.spk
